/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author MATRIX
 */
public class View_productos extends javax.swing.JPanel {

    /**
     * Creates new form View_productos
     */
    public View_productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jl_id_producto = new javax.swing.JLabel();
        jl_producto = new javax.swing.JLabel();
        jl_descripcion = new javax.swing.JLabel();
        jl_precio_compra = new javax.swing.JLabel();
        jl_precio_venta = new javax.swing.JLabel();
        jl_existencias = new javax.swing.JLabel();
        jtf_id_producto = new javax.swing.JTextField();
        jtf_producto = new javax.swing.JTextField();
        jtf_descripcion = new javax.swing.JTextField();
        jtf_precio_compra = new javax.swing.JTextField();
        jtf_precio_venta = new javax.swing.JTextField();
        jtf_existencias = new javax.swing.JTextField();
        jbtnFirst = new javax.swing.JButton();
        jbtnPrevious = new javax.swing.JButton();
        jbtnNext = new javax.swing.JButton();
        jbtnLast = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_editar = new javax.swing.JButton();
        jbtn_buscar = new javax.swing.JButton();
        jl_marca = new javax.swing.JLabel();
        jtf_marca = new javax.swing.JTextField();
        jl_modelo = new javax.swing.JLabel();
        jtf_modelo = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        J_tabla = new javax.swing.JTable();
        jbtn_guardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtn_buscar1 = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        setLayout(null);

        jl_id_producto.setForeground(new java.awt.Color(153, 0, 0));
        jl_id_producto.setText("id_productos");
        add(jl_id_producto);
        jl_id_producto.setBounds(10, 62, 80, 14);

        jl_producto.setForeground(new java.awt.Color(153, 0, 0));
        jl_producto.setText("producto");
        add(jl_producto);
        jl_producto.setBounds(10, 100, 70, 14);

        jl_descripcion.setForeground(new java.awt.Color(153, 0, 0));
        jl_descripcion.setText("descripcion");
        add(jl_descripcion);
        jl_descripcion.setBounds(10, 138, 80, 14);

        jl_precio_compra.setForeground(new java.awt.Color(153, 0, 0));
        jl_precio_compra.setText("precio_compra");
        add(jl_precio_compra);
        jl_precio_compra.setBounds(223, 62, 90, 14);

        jl_precio_venta.setForeground(new java.awt.Color(153, 0, 0));
        jl_precio_venta.setText("precio_venta");
        add(jl_precio_venta);
        jl_precio_venta.setBounds(219, 100, 90, 14);

        jl_existencias.setForeground(new java.awt.Color(153, 0, 0));
        jl_existencias.setText("existencias");
        add(jl_existencias);
        jl_existencias.setBounds(219, 138, 90, 14);

        jtf_id_producto.setEditable(false);
        add(jtf_id_producto);
        jtf_id_producto.setBounds(90, 60, 102, 20);
        add(jtf_producto);
        jtf_producto.setBounds(84, 97, 102, 20);
        add(jtf_descripcion);
        jtf_descripcion.setBounds(84, 135, 102, 20);

        jtf_precio_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_precio_compraActionPerformed(evt);
            }
        });
        add(jtf_precio_compra);
        jtf_precio_compra.setBounds(320, 60, 84, 20);
        add(jtf_precio_venta);
        jtf_precio_venta.setBounds(311, 97, 84, 20);
        add(jtf_existencias);
        jtf_existencias.setBounds(311, 135, 84, 20);

        jbtnFirst.setText("l<");
        jbtnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFirstActionPerformed(evt);
            }
        });
        add(jbtnFirst);
        jbtnFirst.setBounds(90, 208, 50, 23);

        jbtnPrevious.setText("<");
        add(jbtnPrevious);
        jbtnPrevious.setBounds(146, 208, 41, 23);

        jbtnNext.setText(">");
        jbtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNextActionPerformed(evt);
            }
        });
        add(jbtnNext);
        jbtnNext.setBounds(196, 208, 50, 23);

        jbtnLast.setText(">l");
        jbtnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLastActionPerformed(evt);
            }
        });
        add(jbtnLast);
        jbtnLast.setBounds(256, 208, 50, 23);

        jbtn_agregar.setText("Agregar");
        jbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarActionPerformed(evt);
            }
        });
        add(jbtn_agregar);
        jbtn_agregar.setBounds(420, 50, 93, 23);

        jbtn_eliminar.setText("Eliminar");
        add(jbtn_eliminar);
        jbtn_eliminar.setBounds(420, 90, 93, 23);

        jbtn_editar.setText("Editar");
        jbtn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_editarActionPerformed(evt);
            }
        });
        add(jbtn_editar);
        jbtn_editar.setBounds(420, 130, 93, 23);

        jbtn_buscar.setText("Buscar");
        add(jbtn_buscar);
        jbtn_buscar.setBounds(420, 200, 93, 23);

        jl_marca.setForeground(new java.awt.Color(153, 0, 0));
        jl_marca.setText("Marca");
        add(jl_marca);
        jl_marca.setBounds(10, 179, 70, 20);
        add(jtf_marca);
        jtf_marca.setBounds(84, 182, 102, 20);

        jl_modelo.setForeground(new java.awt.Color(153, 0, 0));
        jl_modelo.setText("Modelo");
        add(jl_modelo);
        jl_modelo.setBounds(219, 176, 90, 14);
        add(jtf_modelo);
        jtf_modelo.setBounds(311, 173, 84, 20);

        J_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_producto", "producto", "descripcion", "precio_compra", "precio_venta", "existencias", "marca", "modelo"
            }
        ));
        J_tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J_tablaMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(J_tabla);

        add(jScrollPane6);
        jScrollPane6.setBounds(20, 260, 703, 270);

        jbtn_guardar.setText("Guardar");
        jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarActionPerformed(evt);
            }
        });
        add(jbtn_guardar);
        jbtn_guardar.setBounds(420, 170, 93, 23);

        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/maxresdefault.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-20, -10, 750, 540);

        jbtn_buscar1.setText("Buscar");
        add(jbtn_buscar1);
        jbtn_buscar1.setBounds(420, 200, 93, 23);

        jbtn_actualizar.setText("actulizar");
        add(jbtn_actualizar);
        jbtn_actualizar.setBounds(520, 50, 90, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_precio_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_precio_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_precio_compraActionPerformed

    private void jbtnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnFirstActionPerformed

    private void jbtnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnLastActionPerformed

    private void jbtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnNextActionPerformed

    private void jbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_agregarActionPerformed

    private void jbtn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_editarActionPerformed

    private void jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_guardarActionPerformed

    private void J_tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J_tablaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_J_tablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable J_tabla;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    public javax.swing.JTable jTable3;
    public javax.swing.JTable jTable4;
    public javax.swing.JButton jbtnFirst;
    public javax.swing.JButton jbtnLast;
    public javax.swing.JButton jbtnNext;
    public javax.swing.JButton jbtnPrevious;
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_buscar;
    public javax.swing.JButton jbtn_buscar1;
    public javax.swing.JButton jbtn_editar;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_guardar;
    public javax.swing.JLabel jl_descripcion;
    public javax.swing.JLabel jl_existencias;
    public javax.swing.JLabel jl_id_producto;
    public javax.swing.JLabel jl_marca;
    public javax.swing.JLabel jl_modelo;
    public javax.swing.JLabel jl_precio_compra;
    public javax.swing.JLabel jl_precio_venta;
    public javax.swing.JLabel jl_producto;
    public javax.swing.JTextField jtf_descripcion;
    public javax.swing.JTextField jtf_existencias;
    public javax.swing.JTextField jtf_id_producto;
    public javax.swing.JTextField jtf_marca;
    public javax.swing.JTextField jtf_modelo;
    public javax.swing.JTextField jtf_precio_compra;
    public javax.swing.JTextField jtf_precio_venta;
    public javax.swing.JTextField jtf_producto;
    // End of variables declaration//GEN-END:variables
}
